# Site settings
site: Vipul-Dass.github.io
title: Trying to be Better
keywords: ephesus, blog
description: >-
  A Nook Where I Document the Tid Bits I learn
lang: en-US
timezone: India
repo: https://github.com/Vipul-Dass # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
#google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Vipul Dass
  bio: App Developer at DXC Technology
  picture: assets/images/profile.jpg
  github: Vipul-Dass # github username
  #twitter: onepase # twitter username
  #facebook: onepase # facebook username
  instagram: vdassmann # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: vipul-dass-94b82b9a # linkedin username
  email: vipulhdass@gmail.com # email adress

# URL settings
url: "" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
